create table Member (
    member_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    birthDay varchar(10) NOT NULL,
    email varchar(200) UNIQUE NOT NULL
);

CREATE TABLE Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id int REFERENCES Member(member_id) ON DELETE SET NULL,
    name varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    taken_at timestamp
);

insert into member(name, birthDay, email) values ('Савельева Дарья Григорьевна', '26.08.1996', 'test1@mail.com');
insert into member(name, birthDay, email) values ('Ильин Александр Арсентьевич', '29.03.1972', 'test2@mail.com');
insert into member(name, birthDay, email) values ('Круглова Василиса Николаевна', '10.07.1970', 'test3@mail.com');
insert into member(name, birthDay, email) values ('Иванова Зоя Михайловна', '29.12.1969', 'test4@mail.com');
insert into member(name, birthDay, email) values ('Коновалова Марта Фёдоровна', '11.02.1987', 'test5@mail.com');
insert into member(name, birthDay, email) values ('Денисова Вероника Александровна', '21.11.1975', 'test6@mail.com');
insert into member(name, birthDay, email) values ('Антонова Мелания Владимировна', '30.09.1968', 'test7@mail.com');
insert into member(name, birthDay, email) values ('Белов Максим Тимофеевич', '26.05.1998', 'test8@mail.com');
insert into member(name, birthDay, email) values ('Крылова Вероника Фёдоровна', '26.05.1995', 'test9@mail.com');
insert into member(name, birthDay, email) values ('Некрасов Лев Константинович', '25.01.1999', 'test10@mail.com');

insert into book(member_id, name, author, year, taken_at) values (1, 'Эффективная Java', 'Джошуа Блох', 2014, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (2, 'Чистый код: создание, анализ и рефакторинг', 'Мартин Роберт', 2022, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (3, 'Java. Библиотека профессионала', 'Кей С. Хорстманн', 2020, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (4, 'Head First. Паттерны проектирования', 'Эрик Фримен, Элизабет Робсон', 2018, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (5, 'Spring в действии', 'Крейг Уоллс', 2015, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (6, 'Test Driven: TDD and Acceptance TDD for Java Developers', 'Lasse Koskela', 2007, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (7, 'Изучаем Java', 'Кэти Сиерра, Берт Бейтс', 2012, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (8, 'Алгоритмы на Java', 'Роберт Седжвик, Кевин Уэйн', 2016, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (9, 'Head First Object-Oriented Analysis and Design', 'Brett D. McLaughlin', 2007, '2023-06-1T8:43:28.123456');
insert into book(member_id, name, author, year, taken_at) values (10, 'Java. Полное руководство', 'Герберт Шилдт', 2015, '2023-06-1T8:43:28.123456');

-- (Аналогичное заполнение таблицы Book, только без привязки к пользователям)

-- insert into book(name, author, year, taken_at) values ('Эффективная Java', 'Джошуа Блох', 2014, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Чистый код: создание, анализ и рефакторинг', 'Мартин Роберт', 2022, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Java. Библиотека профессионала', 'Кей С. Хорстманн', 2020, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Head First. Паттерны проектирования', 'Эрик Фримен, Элизабет Робсон', 2018, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Spring в действии', 'Крейг Уоллс', 2015, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Test Driven: TDD and Acceptance TDD for Java Developers', 'Lasse Koskela', 2007, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Изучаем Java', 'Кэти Сиерра, Берт Бейтс', 2012, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Алгоритмы на Java', 'Роберт Седжвик, Кевин Уэйн', 2016, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ('Head First Object-Oriented Analysis and Design', 'Brett D. McLaughlin', 2007, '2023-06-1T8:43:28.123456');
-- insert into book(name, author, year, taken_at) values ( 'Java. Полное руководство', 'Герберт Шилдт', 2015, '2023-06-1T8:43:28.123456');
